version: '3.8'
services:
  jenkins:
    build:
      dockerfile: Dockerfile
    privileged: true
    restart: always
    user: root
    ports:
      - "4440:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - ./jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock